version: '3'

services:
  ruby:
    image: ruby
    command: irb
    ports:
     - "5000:5000"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/reis:/data"     
