name: example

on:
  push:
    branches:
      - master
      
jobs:
  build:
    name: Set up
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: docker://ruby:2.7
      - name: Set up Redis
        uses: docker://redis
      - name: docker compose
        run: docker-compose build
