name: example

on:
  push:
    branches:
      - self-hosted

jobs:
  build:
    name: Set up
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: docker://ruby:2.7
      - name: Set up Postgres
        uses: docker://postgres
      - name: Set up Redis
        uses: docker://redis
      - name: docker compose
        run: docker-compose build
