name: example

on:
  push:
    branches:
      - master
      
jobs:
  one:
    name: Set up
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker compose
        run:  docker build -t admin/echo ./ && docker save admin/echo > sample.tar
      - uses: actions/upload-artifact@v1
        with:
          name: homework
          path: sample.tar

  two:
    name: download
    runs-on: [ubuntu-latest]
    needs: one
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v1
        with:
          name: homework
      - shell: bash
        run: cat homework/math-homework.txt
