name: example

on:
  push:
    branches:
      - self-hosted

jobs:
  build:
    name: Set up
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello
        run: echo "hello"
