name: example

on:
  push:
    branches:
      - production
      
jobs:
  one:
    name: Set up
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker compose
         run: echo {{ asdfg }}
  #     - uses: actions/upload-artifact@v1
  #       with:
  #         name: homework
  #         path: sample.tar

  two:
    name: Download
    runs-on: [ubuntu-latest]
#    needs: one
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v1
        with:
          name: homework
      - shell: bash
        run: docker load < homework/sample.tar
      - run: docker run admin/echo ruby -v
