name: example

on:
  push:
    branches:
      - master
      
jobs:
  build:
    name: Set up
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        run: docker-compose build || docker-compose up
