name: example

on:
  push:
    branches:
      - master
      
jobs:
  build:
    name: Set up
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/cache@v1
        with:
          path: /var/lib/docker/
      - uses: actions/checkout@v2
      - name: Set up Docker compose
        run: docker-compose build || docker-compose up -d
      - name: Do test
        run: docker-compose run ruby date
      - name: Finish
        run: docker-compose run redis date
