name: example

on:
  push:
    branches:
      - master
    jobs:
      build:
        name: Set up
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
        - name: Set up Jekyll
          run: |
            echo "helo"
