name: example

on:
  push:
    branches:
      - master
      
jobs:
  build:
    name: Set up
    runs-on: [ubuntu-latest]
    # container:
    #   image: alpine
    steps:
      - uses: actions/upload-artifact@v1
        with:
          name: homework
          path: math-homework.txt
      - name: Set up Docker compose
        run:  expr 3 + 3 > math-homework.txt
