name: SEAHAL.COM

on:
  push:
    branches:
      - master
    schedule:
      - cron: '*/21 * * * *'
          

jobs:
  build:
    name: Set up
    runs-on: ubuntu-latest

    steps:
      - name: Greeting
        uses: actions/checkout@v2
        with:
          who-to-greet: 'Mona the octocat'
          id: hello
        run: echo {$PWD}
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'


