name: SEAHAL.COM

on:
  push:
    branches:
      - master
    # schedule:
    #   - cron: '*/21 * * * *'
          

jobs:
  build:
    name: Set up
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from repository
        uses: actions/checkout@v2
      - name: Set up ruby
        uses: actions/setup-ruby@v1
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Set up Jekyll
        run: |
          cd ./jekyll/
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
